const { Client } = require('pg');
require('dotenv').config({ path: '.env' });

const FINANCE_JOBS = [
  {
    id: "ch-gnty-universal-banker",
    title: "Universal Banker",
    company_slug: "gnty-bank",
    company_name: "Guaranty Bank",
    company_industry: "Banking",
    company_logo: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=128&auto=format&fit=crop&q=80",
    company_website: "https://guarantybank.com",
    description_excerpt: "Provide direct client advisory, open commercial and consumer deposit accounts, manage teller transactions, vault balancing, and regulatory compliance under Bank Secrecy Act and FDIC guidelines.",
    description_full: "Guaranty Bank is looking for an experienced Universal Banker. You will be the primary point of contact for customer deposit operations, teller transaction balancing, Bank Secrecy Act (BSA) compliance, and relationship cross-selling.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "0-to-2",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Indianola, Mississippi, United States"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 45000,
    salary_max: 60000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Retail banking", "Universal Banker", "Deposit accounts", "Cash management", "Vault balancing", "FDIC insurance", "Bank Secrecy Act"]),
    application_url: "https://boards.greenhouse.io/guarantybank/jobs/920194",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 3 * 3600 * 1000)
  },
  {
    id: "ch-village-bank-float-supervisor",
    title: "Float Branch Supervisor",
    company_slug: "the-village-bank",
    company_name: "The Village Bank",
    company_industry: "Banking",
    company_logo: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=128&auto=format&fit=crop&q=80",
    company_website: "https://village-bank.com",
    description_excerpt: "Supervise branch floor operations, cash drawer reconciliation, vault settlement, dual-control audit procedures, and staff lending guidance across regional retail banking locations.",
    description_full: "The Village Bank is seeking a Float Branch Supervisor to support regional branches across Massachusetts. You will oversee cash drawer balancing, vault settlement, dual-control regulatory compliance, and staff supervision.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "associate-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Newton, Massachusetts, United States"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 48000,
    salary_max: 55000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Banking", "Branch Supervisor", "Deposit products", "Cash drawer balancing", "Vault settlement", "Auditing", "Staff supervision"]),
    application_url: "https://jobs.lever.co/villagebank/481928",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 5 * 3600 * 1000)
  },
  {
    id: "ch-wns-asst-mgr-ops",
    title: "Assistant Manager - Financial Operations",
    company_slug: "wns-global-services",
    company_name: "WNS Global Services",
    company_industry: "Business Consulting and Services",
    company_logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=128&auto=format&fit=crop&q=80",
    company_website: "https://wns.com",
    description_excerpt: "Lead accounts receivable, dispute reconciliation, billing operations, collections tracking, aging report generation, and periodic month-end accounting close coordination.",
    description_full: "WNS Global Services is hiring an Assistant Manager of Financial Operations. You will manage end-to-end accounts receivable (AR), billing disputes, aging schedules, and month-end closing procedures.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Chennai, Tamil Nadu, India"]),
    is_worldwide: false,
    salary_currency: "INR",
    salary_min: 800000,
    salary_max: 1200000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Invoicing", "Accounts Receivable", "Collections", "Reconciliation", "Financial Reporting", "Aging Reports", "Month-end Closing"]),
    application_url: "https://jobs.ashbyhq.com/wns/829103",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 8 * 3600 * 1000)
  },
  {
    id: "ch-marriott-accounting-asst-mgr",
    title: "Accounting Assistant Manager",
    company_slug: "marriott-international",
    company_name: "Marriott International Hotels",
    company_industry: "Hospitality",
    company_logo: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=128&auto=format&fit=crop&q=80",
    company_website: "https://marriott.com",
    description_excerpt: "Manage day-to-day general ledger journal postings, payroll reconciliation, vendor invoice audit, period-end account balancing, and luxury property financial reporting.",
    description_full: "Join The Ritz-Carlton / Marriott International as Accounting Assistant Manager. You will oversee hotel financial operations, vendor statement reconciliation, night audit verification, and ledger journals.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "0-to-2",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Nago, Okinawa Prefecture, Japan", "Tokyo, Japan"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 52000,
    salary_max: 68000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Accounting", "Financial records", "Invoicing", "Auditing", "Payroll", "Period-end closing", "General Ledger"]),
    application_url: "https://jobs.marriott.com/careers/928109",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 9 * 3600 * 1000)
  },
  {
    id: "ch-griffith-principal-accountant",
    title: "Principal Financial Accountant",
    company_slug: "griffith-university",
    company_name: "Griffith University",
    company_industry: "Higher Education",
    company_logo: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=128&auto=format&fit=crop&q=80",
    company_website: "https://griffith.edu.au",
    description_excerpt: "Lead university statutory compliance, complex tax structuring, annual audit coordination, treasury cash flow management, and multi-fund revenue recognition across faculties.",
    description_full: "Griffith University is appointing a Principal Financial Accountant (CA/CPA qualified) to oversee statutory reporting, capital works accounting, Australian taxation compliance, and external audit governance.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Nathan, Queensland, Australia", "Brisbane, Australia"]),
    is_worldwide: false,
    salary_currency: "AUD",
    salary_min: 160483,
    salary_max: 166222,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Financial Accounting", "CA", "CPA", "Financial Reporting", "Statutory Compliance", "Audit Coordination", "Treasury"]),
    application_url: "https://jobs.griffith.edu.au/jobs/48201",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 10 * 3600 * 1000)
  },
  {
    id: "ch-jpmorgan-corporate-tax-director",
    title: "Executive Director, Asia Corporate Tax",
    company_slug: "jpmorganchase",
    company_name: "JPMorgan Chase & Co.",
    company_industry: "Financial Services",
    company_logo: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=128&auto=format&fit=crop&q=80",
    company_website: "https://jpmorganchase.com",
    description_excerpt: "Direct regional corporate tax strategy, cross-border M&A tax advisory, governance risk controls, and regulatory tax reporting for APAC investment banking and asset management divisions.",
    description_full: "JPMorgan Chase is seeking an Executive Director for Asia Corporate Tax. You will lead cross-border tax structurings, oversee Transfer Pricing documentation, and represent the firm before regional regulatory bodies.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "10-plus",
    education_level: "postgraduate-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Mumbai, Maharashtra, India", "Singapore", "Hong Kong"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 180000,
    salary_max: 260000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Corporate Tax", "Chartered Accountant", "Financial Services", "Cross-border Tax", "Transfer Pricing", "Investment Banking", "Governance"]),
    application_url: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/21049281",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 12 * 3600 * 1000)
  },
  {
    id: "ch-vercel-sr-finance-mgr-sales",
    title: "Senior Finance Manager, Sales & RevOps",
    company_slug: "vercel",
    company_name: "Vercel",
    company_industry: "Software Development",
    company_logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80",
    company_website: "https://vercel.com",
    description_excerpt: "Own financial planning & analysis (FP&A) for enterprise sales, quota capacity modeling, commission incentive architecture, pipeline forecasting, and executive BvA reporting.",
    description_full: "At Vercel, we are building the developer frontend platform. As Senior Finance Manager for Sales & RevOps, you will partner directly with the CRO to model ARR quotas, enterprise sales incentives, and multi-year forecasting.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["San Francisco, California, United States", "Remote Solely", "Worldwide"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 200000,
    salary_max: 240000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Finance", "Sales", "RevOps", "FP&A", "Budgeting", "Commissions", "Quota planning", "Scenario analysis", "Excel"]),
    application_url: "https://jobs.ashbyhq.com/vercel/9381023",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 14 * 3600 * 1000)
  },
  {
    id: "ch-crawford-external-claims-adjuster",
    title: "External Claims Adjuster (Property & Commercial)",
    company_slug: "crawford-and-company",
    company_name: "Crawford & Company",
    company_industry: "Insurance",
    company_logo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=128&auto=format&fit=crop&q=80",
    company_website: "https://crawco.com",
    description_excerpt: "Investigate, assess, and settle complex property, liability, and commercial insurance loss claims. Perform on-site structural damage evaluations, policy interpretation, and reserve calculations.",
    description_full: "Crawford & Company is seeking an External Claims Adjuster. You will investigate complex property and commercial loss incidents, determine coverage under policy terms, and negotiate settlements.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Sydney, New South Wales, Australia", "Melbourne, Australia"]),
    is_worldwide: false,
    salary_currency: "AUD",
    salary_min: 95000,
    salary_max: 125000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Loss adjusting", "Claims management", "Property claims", "Commercial property", "Insurance", "CILA", "ANZIIF", "Risk assessment"]),
    application_url: "https://jobs.crawco.com/job/381920",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 16 * 3600 * 1000)
  },
  {
    id: "ch-metro-public-adjustment-claims",
    title: "Claims Representative & Settlement Analyst",
    company_slug: "metro-public-adjustment",
    company_name: "Metro Public Adjustment Inc.",
    company_industry: "Insurance",
    company_logo: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=128&auto=format&fit=crop&q=80",
    company_website: "https://metropa.com",
    description_excerpt: "Advocate for commercial and residential policyholders in property damage appraisals, financial loss documentation, insurer negotiations, and maximum policy payout recovery.",
    description_full: "Metro Public Adjustment Inc. is recruiting a Claims Representative. You will represent homeowners and commercial businesses to evaluate property damages and audit insurance claims.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["Full time", "Part time"]),
    experience_level: "0-to-2",
    education_level: "no-requirements",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Hartford, Connecticut, United States", "Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 65000,
    salary_max: 95000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Claims Representative", "Public Adjusting", "Insurance", "Property Inspection", "Policyholder", "Settlement", "Remote Work"]),
    application_url: "https://metropa.com/careers/618275",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 18 * 3600 * 1000)
  },
  {
    id: "ch-dp-world-asst-mgr-treasury",
    title: "Assistant Manager - Global Treasury",
    company_slug: "dp-world",
    company_name: "DP World",
    company_industry: "Logistics & Supply Chain",
    company_logo: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=128&auto=format&fit=crop&q=80",
    company_website: "https://dpworld.com",
    description_excerpt: "Manage global multi-currency liquidity, Kyriba TMS cash management, FX hedging transactions, bank guarantee issuance, and bank counterparty reconciliation schedules.",
    description_full: "DP World's Global Service Centre is hiring an Assistant Manager - Treasury. You will manage Kyriba treasury management systems, bank guarantees, FX hedging, and cash flow reconciliation.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Navi Mumbai, Maharashtra, India", "Dubai, United Arab Emirates"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 35000,
    salary_max: 50000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Treasury", "Kyriba", "Cash Management", "Financial Reporting", "Bank Guarantees", "ALCO", "FX", "Bank Reconciliation"]),
    application_url: "https://careers.dpworld.com/job/492019",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 20 * 3600 * 1000)
  },
  {
    id: "ch-computershare-finance-officer",
    title: "Corporate Finance Officer (PRC & IFRS)",
    company_slug: "computershare",
    company_name: "Computershare",
    company_industry: "Financial Services",
    company_logo: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=128&auto=format&fit=crop&q=80",
    company_website: "https://computershare.com",
    description_excerpt: "Handle cross-border dividend settlements, Fusion and Kingdee ERP general ledger reconciliation, IFRS and PRC standard variance analysis, and multi-entity accounts payable.",
    description_full: "Computershare is looking for a Finance Officer in Beijing. You will oversee multi-entity financial administration, cross-border dividend distribution, Kingdee financial posting, and IFRS reconciliation.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Beijing, Beijing, China", "Hong Kong"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 40000,
    salary_max: 55000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Finance", "Accounting", "IFRS", "PRC Standards", "Kingdee", "Fusion", "Cross-border payment", "P&L report"]),
    application_url: "https://computershare.wd3.myworkdayjobs.com/Careers/job/Beijing/Finance-Officer",
    direct_apply_source: "workday",
    published_at: new Date(Date.now() - 22 * 3600 * 1000)
  },
  {
    id: "ch-motive-senior-accountant",
    title: "Senior US GAAP Accountant",
    company_slug: "motive-agency",
    company_name: "Motive Agency",
    company_industry: "Advertising & Marketing",
    company_logo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&auto=format&fit=crop&q=80",
    company_website: "https://motive.com",
    description_excerpt: "Own US GAAP month-end close schedules, NetSuite ERP journal entries, balance sheet reconciliation, technical accounting policy memos, and annual audit workpapers.",
    description_full: "Motive is seeking a Senior Accountant with strong US GAAP and NetSuite expertise. You will manage monthly financial closes, fluctuation analyses, internal controls, and technical audit preparation.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Bangalore, Karnataka, India"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 30000,
    salary_max: 42000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Senior Accountant", "Financial Reporting", "US GAAP", "Month-end Close", "NetSuite", "ERP", "General Ledger", "CPA"]),
    application_url: "https://jobs.lever.co/motive/829104",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 24 * 3600 * 1000)
  },
  {
    id: "ch-northwell-financial-ops-analyst",
    title: "Financial Operations Analyst",
    company_slug: "northwell-health",
    company_name: "Northwell Health",
    company_industry: "Healthcare",
    company_logo: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=128&auto=format&fit=crop&q=80",
    company_website: "https://northwell.edu",
    description_excerpt: "Evaluate healthcare service line revenue integrity, medical accounts receivable reconciliation, hospital budget variance tracking, and GL reserve allocation auditing.",
    description_full: "Northwell Health is looking for a Financial Operations Analyst in New York. You will perform financial forecasting, medical account coding review, statistical cost tracking, and internal audit reconciliation.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "0-to-2",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["New Hyde Park, New York, United States"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 66300,
    salary_max: 86060,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Financial Operations", "Accounts Receivable", "Cash Flow", "Budgets", "General Ledger", "P&L", "Healthcare Finance"]),
    application_url: "https://jobs.northwell.edu/job/930182",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 26 * 3600 * 1000)
  },
  {
    id: "ch-kordamentha-mgr-loan-servicing",
    title: "Manager - Loan Servicing & Syndicated Lending",
    company_slug: "kordamentha",
    company_name: "KordaMentha",
    company_industry: "Financial Advisory",
    company_logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=128&auto=format&fit=crop&q=80",
    company_website: "https://kordamentha.com",
    description_excerpt: "Manage facility agency operations for syndicated corporate loans, complex debt restructuring distributions, payment flow tracking, and covenant compliance reporting.",
    description_full: "KordaMentha is appointing a Manager of Loan Servicing. You will act as Facility Agent for major syndicated loans, oversee covenant tracking, and lead capital solutions debt execution.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Sydney, New South Wales, Australia", "Melbourne, Australia"]),
    is_worldwide: false,
    salary_currency: "AUD",
    salary_min: 140000,
    salary_max: 175000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Loan Servicing", "Syndicated Lending", "Facility Agent", "Lending Operations", "Debt Restructuring", "Banking", "Capital Solutions"]),
    application_url: "https://kordamentha.com/careers/481920",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 28 * 3600 * 1000)
  },
  {
    id: "ch-sgs-deputy-finance-controller",
    title: "Deputy Finance Controller",
    company_slug: "sgs",
    company_name: "SGS Group",
    company_industry: "Professional Services",
    company_logo: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=128&auto=format&fit=crop&q=80",
    company_website: "https://sgs.com",
    description_excerpt: "Lead multi-division financial controlling, Hyperion and Oracle ERP financial consolidations, KICPA/AICPA compliance, working capital risk, and statutory tax reviews.",
    description_full: "SGS Group is hiring a Deputy Finance Controller in South Korea. You will oversee business unit controllership, FP&A modeling, internal control audits, and multinational statutory financial reporting.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "10-plus",
    education_level: "postgraduate-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Dongtan, Gyeonggi-do, South Korea", "Seoul, South Korea"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 110000,
    salary_max: 145000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Finance", "Accounting", "FP&A", "Tax", "Treasury", "KICPA", "AICPA", "Oracle", "Hyperion", "Financial Statements"]),
    application_url: "https://jobs.sgs.com/careers/kr-93019",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 30 * 3600 * 1000)
  },
  {
    id: "ch-esrgroup-development-analyst",
    title: "Real Estate Development & Investment Analyst",
    company_slug: "esrgroup",
    company_name: "ESR Group",
    company_industry: "Real Estate & Logistics Infrastructure",
    company_logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=128&auto=format&fit=crop&q=80",
    company_website: "https://esr.com",
    description_excerpt: "Build DCF financial models for logistics parks and data center infrastructure developments, project feasibility studies, fund cash flow forecasting, and debt draw schedules.",
    description_full: "ESR Group is recruiting a Development Analyst to build underwriting models for tier-1 industrial logistics assets and data centers across APAC. You will prepare investment committee memos and cash flow forecasts.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Melbourne, Victoria, Australia", "Sydney, Australia"]),
    is_worldwide: false,
    salary_currency: "AUD",
    salary_min: 115000,
    salary_max: 145000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Development Analyst", "Real estate", "Logistics", "Financial modelling", "Feasibility", "Cash flow", "Fund management"]),
    application_url: "https://esr.com/careers/au-49102",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 32 * 3600 * 1000)
  },
  {
    id: "ch-westpac-local-business-banker",
    title: "Local Business Banker",
    company_slug: "westpac-group",
    company_name: "Westpac Group",
    company_industry: "Banking",
    company_logo: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=128&auto=format&fit=crop&q=80",
    company_website: "https://westpac.com.au",
    description_excerpt: "Manage portfolio of small-to-medium enterprise commercial borrowers, underwrite working capital lines and commercial mortgages, and structure deposit treasury facilities.",
    description_full: "Westpac Group is appointing a Local Business Banker in Victoria. You will build relationships with local commercial business owners, structure commercial lending solutions, and grow deposit accounts.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Brighton, Victoria, Australia", "Melbourne, Australia"]),
    is_worldwide: false,
    salary_currency: "AUD",
    salary_min: 88000,
    salary_max: 115000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Banking", "Small Business Banking", "Commercial Lending", "Relationship Management", "Financial Services", "Underwriting"]),
    application_url: "https://westpac.taleo.net/careersection/wbc/jobdetail.ftl?job=930194",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 34 * 3600 * 1000)
  },
  {
    id: "ch-nz-housing-finance-mgr",
    title: "Manager, Finance Reporting and Control",
    company_slug: "nz-ministry-housing",
    company_name: "Te Tūāpapa Kura Kāinga - Ministry of Housing NZ",
    company_industry: "Government Administration",
    company_logo: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=128&auto=format&fit=crop&q=80",
    company_website: "https://hud.govt.nz",
    description_excerpt: "Direct Crown statutory financial reporting, balance sheet governance, Oracle Cloud ERP controls, capital appropriation reconciliations, and external Audit New Zealand liaison.",
    description_full: "Lead Crown financial reporting and governance for the Ministry of Housing and Urban Development. You will oversee statutory reports, Treasury appropriations, balance sheet governance, and public sector risk.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "10-plus",
    education_level: "postgraduate-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["Pipitea, Wellington Region, New Zealand", "Auckland, New Zealand"]),
    is_worldwide: false,
    salary_currency: "NZD",
    salary_min: 155346,
    salary_max: 219312,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Financial Reporting", "Financial Control", "Treasury", "Statutory Reporting", "Oracle", "CA", "CPA", "Government"]),
    application_url: "https://hud.govt.nz/careers/position/930182",
    direct_apply_source: "company-direct",
    published_at: new Date(Date.now() - 36 * 3600 * 1000)
  },
  {
    id: "ch-stripe-staff-revenue-accountant",
    title: "Staff Revenue & Technical Accountant",
    company_slug: "stripe",
    company_name: "Stripe",
    company_industry: "Financial Infrastructure",
    company_logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80",
    company_website: "https://stripe.com",
    description_excerpt: "Architect automated ASC 606 revenue recognition engines for new Stripe financial products, evaluate complex multi-currency fee schedules, and drive financial audits.",
    description_full: "Stripe is seeking a Staff Revenue Accountant to architect ASC 606 automated accounting rules for global billing products. You will partner with payment infrastructure engineers to build financial integrity pipelines.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 150000,
    salary_max: 195000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Revenue Recognition", "ASC 606", "Technical Accounting", "US GAAP", "SQL", "Fintech", "Audit", "CPA"]),
    application_url: "https://boards.greenhouse.io/stripe/jobs/5910294",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 38 * 3600 * 1000)
  },
  {
    id: "ch-linear-fpa-lead",
    title: "Head of FP&A and Financial Strategy",
    company_slug: "linear",
    company_name: "Linear",
    company_industry: "Developer Tools",
    company_logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    company_website: "https://linear.app",
    description_excerpt: "Lead financial modeling, capital allocation, pricing experiments, hiring plan budgets, and executive board reporting at hyper-growth developer tools company.",
    description_full: "Linear is hiring its first Head of FP&A. You will own long-range financial modeling, unit economics analysis, board decks, and pricing strategies for enterprise tiers.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 165000,
    salary_max: 220000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["FP&A", "Financial Modeling", "Corporate Finance", "SaaS Metrics", "Pricing", "Excel", "SQL"]),
    application_url: "https://jobs.ashbyhq.com/linear/482019",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 40 * 3600 * 1000)
  }
];

const CROSS_CATEGORY_JOBS = [
  {
    id: "ch-stripe-staff-infra",
    title: "Staff Infrastructure Engineer (Distributed Systems)",
    company_slug: "stripe",
    company_name: "Stripe",
    company_industry: "Financial Infrastructure",
    company_logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80",
    company_website: "https://stripe.com",
    description_excerpt: "Architect and scale foundational global payment processing pipelines handling billions in daily volume. Work with Go, Kubernetes, and low-latency storage systems.",
    description_full: "Stripe is seeking a Staff Infrastructure Engineer to design, build, and operate the core distributed systems that power our global economic engine.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "10-plus",
    education_level: "bachelor-degree",
    taxonomy: "engineering",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 210000,
    salary_max: 295000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Go", "Distributed Systems", "Kubernetes", "PostgreSQL", "Kafka", "AWS"]),
    application_url: "https://boards.greenhouse.io/stripe/jobs/4829101",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 2 * 3600 * 1000)
  },
  {
    id: "ch-linear-fullstack-product",
    title: "Senior Full Stack Product Engineer",
    company_slug: "linear",
    company_name: "Linear",
    company_industry: "Developer Tools & Productivity",
    company_logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    company_website: "https://linear.app",
    description_excerpt: "Help build the fastest, most delightful issue tracking and project management software in the world. High-performance TypeScript, React, and local-first sync engines.",
    description_full: "At Linear, we care deeply about craft, speed, and precision. You will work across our client and server sync architecture with WebSockets, IndexedDB, and SQLite.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "no-requirements",
    taxonomy: "software",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide", "Europe / US Timezones"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 175000,
    salary_max: 235000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["TypeScript", "React", "Node.js", "Local-First Architecture", "WebSockets", "CSS"]),
    application_url: "https://jobs.ashbyhq.com/linear/28a9b311",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 4 * 3600 * 1000)
  },
  {
    id: "ch-anthropic-ai-engineer",
    title: "AI Applications & Prompt Systems Engineer",
    company_slug: "anthropic",
    company_name: "Anthropic",
    company_industry: "Artificial Intelligence Safety",
    company_logo: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=128&auto=format&fit=crop&q=80",
    company_website: "https://anthropic.com",
    description_excerpt: "Build state-of-the-art interactive tool-use interfaces, evaluation harnesses, and frontier LLM agents powered by Claude 3.5 Sonnet and Opus.",
    description_full: "Anthropic is looking for an AI Applications Engineer to design developer SDKs, tool calling orchestrators, and high-reliability reasoning workflows.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "technology",
    locations: JSON.stringify(["San Francisco, CA", "Seattle, WA", "New York, NY"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 190000,
    salary_max: 260000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Python", "Claude API", "LLMs", "Evaluation Frameworks", "TypeScript", "FastAPI"]),
    application_url: "https://jobs.lever.co/anthropic/7182910",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 6 * 3600 * 1000)
  },
  {
    id: "ch-datadog-senior-data-eng",
    title: "Senior Real-Time Data Platform Engineer",
    company_slug: "datadog",
    company_name: "Datadog",
    company_industry: "Cloud Observability & Security",
    company_logo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80",
    company_website: "https://datadoghq.com",
    description_excerpt: "Scale distributed streaming pipelines ingesting tens of trillions of events daily. Optimize Kafka, Apache Flink, and ClickHouse cluster topologies.",
    description_full: "Datadog's Platform team is looking for a Senior Data Engineer to scale petabyte-scale stream processing engines.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "data-and-analytics",
    locations: JSON.stringify(["New York, NY", "Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 165000,
    salary_max: 225000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Apache Kafka", "Flink", "ClickHouse", "Go", "Java", "Distributed Systems", "Kubernetes"]),
    application_url: "https://boards.greenhouse.io/datadog/jobs/3819201",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 10 * 3600 * 1000)
  },
  {
    id: "ch-figma-lead-product-designer",
    title: "Lead Product Designer (Design Systems)",
    company_slug: "figma",
    company_name: "Figma",
    company_industry: "Design & Collaborative Software",
    company_logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    company_website: "https://figma.com",
    description_excerpt: "Shape the evolution of Figma Design Systems, token workflows, and cross-platform component architectures used by millions of designers and developers worldwide.",
    description_full: "Figma is seeking a Lead Product Designer to envision the future of design tooling, token semantics, and accessibility standards.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "art-and-design",
    locations: JSON.stringify(["San Francisco, CA", "New York, NY", "London, UK"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 180000,
    salary_max: 240000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Design Systems", "Figma", "UI/UX", "Prototyping", "Information Architecture", "Design Tokens"]),
    application_url: "https://boards.greenhouse.io/figma/jobs/930182",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 14 * 3600 * 1000)
  },
  {
    id: "ch-snowflake-enterprise-ae",
    title: "Enterprise Account Executive (Cloud Data Cloud)",
    company_slug: "snowflake",
    company_name: "Snowflake",
    company_industry: "Enterprise Cloud Data",
    company_logo: "https://images.unsplash.com/photo-1542744094-24638eff58bb?w=128&auto=format&fit=crop&q=80",
    company_website: "https://snowflake.com",
    description_excerpt: "Drive net-new enterprise customer acquisition for Snowflake's AI Data Cloud across Fortune 500 accounts in the Northeast territory.",
    description_full: "Snowflake is hiring an Enterprise Account Executive to manage strategic multi-million dollar Cloud Data engagements.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["Full time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "sales",
    locations: JSON.stringify(["New York, NY", "Boston, MA"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 160000,
    salary_max: 320000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Enterprise Software Sales", "MEDDPICC", "Cloud Architecture", "Data Warehousing", "Contract Negotiation"]),
    application_url: "https://boards.greenhouse.io/snowflake/jobs/829102",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 20 * 3600 * 1000)
  }
];

const ALL_SEED_JOBS = [...FINANCE_JOBS, ...CROSS_CATEGORY_JOBS];

async function seed() {
  const uri = process.env.DATABASE_URL || 'postgresql://postgres:50h41L%40$$@localhost:5432/careerhound';
  const client = new Client({ connectionString: uri });

  try {
    await client.connect();
    console.log('Connected to PostgreSQL for seeding jobs...');

    // Clear old test rows
    await client.query('DELETE FROM jobs');

    for (const job of ALL_SEED_JOBS) {
      await client.query(`
        INSERT INTO jobs (
          id, title, company_slug, company_name, company_industry,
          company_logo, company_website, description_excerpt, description_full,
          work_arrangement, employment_types, experience_level, education_level,
          taxonomy, locations, is_worldwide, salary_currency, salary_min,
          salary_max, salary_unit, skills, application_url, direct_apply_source,
          published_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
        ) ON CONFLICT (id) DO UPDATE SET
          title = EXCLUDED.title,
          description_excerpt = EXCLUDED.description_excerpt,
          salary_min = EXCLUDED.salary_min,
          salary_max = EXCLUDED.salary_max,
          skills = EXCLUDED.skills,
          application_url = EXCLUDED.application_url;
      `, [
        job.id,
        job.title,
        job.company_slug,
        job.company_name,
        job.company_industry,
        job.company_logo,
        job.company_website,
        job.description_excerpt,
        job.description_full,
        job.work_arrangement,
        job.employment_types,
        job.experience_level,
        job.education_level,
        job.taxonomy,
        job.locations,
        job.is_worldwide,
        job.salary_currency,
        job.salary_min,
        job.salary_max,
        job.salary_unit,
        job.skills,
        job.application_url,
        job.direct_apply_source,
        job.published_at
      ]);
    }

    const countRes = await client.query('SELECT COUNT(*) FROM jobs');
    const catRes = await client.query('SELECT taxonomy, COUNT(*) FROM jobs GROUP BY taxonomy ORDER BY count DESC');
    console.log(`Successfully seeded ${countRes.rows[0].count} verified direct jobs into PostgreSQL!`);
    console.log('Categories breakdown:');
    catRes.rows.forEach(r => console.log(`  - ${r.taxonomy}: ${r.count} jobs`));
    await client.end();
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seed();
