const { Client } = require('pg');

const JOBS = [
  {
    id: "ch-stripe-staff-infra",
    title: "Staff Infrastructure Engineer (Distributed Systems)",
    company_slug: "stripe",
    company_name: "Stripe",
    company_industry: "Financial Infrastructure",
    company_logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80",
    company_website: "https://stripe.com",
    description_excerpt: "Architect and scale foundational global payment processing pipelines handling billions in daily volume. Work with Go, Kubernetes, and low-latency storage systems.",
    description_full: "Stripe is seeking a Staff Infrastructure Engineer to design, build, and operate the core distributed systems that power our global economic engine. You will own architecture decisions for high-availability database engines, service meshes, and cross-region consensus mechanisms.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "10-plus",
    education_level: "bachelor-degree",
    taxonomy: "engineering",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 210000,
    salary_max: 295000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Go", "Distributed Systems", "Kubernetes", "PostgreSQL", "Kafka", "AWS"]),
    application_url: "https://boards.greenhouse.io/stripe/jobs/4829101",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 2 * 3600 * 1000)
  },
  {
    id: "ch-linear-fullstack-product",
    title: "Senior Full Stack Product Engineer",
    company_slug: "linear",
    company_name: "Linear",
    company_industry: "Developer Tools & Productivity",
    company_logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    company_website: "https://linear.app",
    description_excerpt: "Help build the fastest, most delightful issue tracking and project management software in the world. High-performance TypeScript, React, and local-first sync engines.",
    description_full: "At Linear, we care deeply about craft, speed, and precision. You will work across our client and server sync architecture, crafting sub-50ms user experiences with WebSockets, IndexedDB, and SQLite.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "no-requirements",
    taxonomy: "software",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide", "Europe / US Timezones"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 175000,
    salary_max: 235000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["TypeScript", "React", "Node.js", "Local-First Architecture", "WebSockets", "CSS"]),
    application_url: "https://jobs.ashbyhq.com/linear/28a9b311",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 4 * 3600 * 1000)
  },
  {
    id: "ch-anthropic-ai-engineer",
    title: "AI Applications & Prompt Systems Engineer",
    company_slug: "anthropic",
    company_name: "Anthropic",
    company_industry: "Artificial Intelligence",
    company_logo: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=128&auto=format&fit=crop&q=80",
    company_website: "https://anthropic.com",
    description_excerpt: "Build frontier agentic workflows, multi-turn reasoning evaluation frameworks, and developer APIs powered by the Claude 3.5 model family.",
    description_full: "Anthropic is looking for software engineers who excel at bridging state-of-the-art foundation models with production customer systems. You will build high-throughput inference caching, prompt orchestration pipelines, and safety monitors.",
    work_arrangement: "Remote OK",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "technology",
    locations: JSON.stringify(["San Francisco, CA", "New York, NY", "Worldwide Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 185000,
    salary_max: 260000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Python", "TypeScript", "FastAPI", "Prompt Engineering", "Evaluation Frameworks", "Vector Databases"]),
    application_url: "https://jobs.lever.co/anthropic/e81249b0",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 6 * 3600 * 1000)
  },
  {
    id: "ch-supabase-backend-pg",
    title: "Senior Backend Engineer (PostgreSQL & Go)",
    company_slug: "supabase",
    company_name: "Supabase",
    company_industry: "Developer Infrastructure & Databases",
    company_logo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80",
    company_website: "https://supabase.com",
    description_excerpt: "Develop core cloud infrastructure managing hundreds of thousands of PostgreSQL clusters. Open-source first, high concurrency, and real-time streaming.",
    description_full: "Supabase is an open source Firebase alternative built on PostgreSQL. We are looking for backend engineers to build and maintain our control plane, database pooling layers, and backup services.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "no-requirements",
    taxonomy: "software",
    locations: JSON.stringify(["Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 160000,
    salary_max: 220000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Go", "PostgreSQL", "Elixir", "Docker", "Linux", "Distributed Systems"]),
    application_url: "https://jobs.ashbyhq.com/supabase/f4710bc2",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 8 * 3600 * 1000)
  },
  {
    id: "ch-figma-lead-product-designer",
    title: "Lead Product Designer (Design Systems & Web)",
    company_slug: "figma",
    company_name: "Figma",
    company_industry: "Design & Collaboration Software",
    company_logo: "https://images.unsplash.com/photo-1542744094-3a31727221eb?w=128&auto=format&fit=crop&q=80",
    company_website: "https://figma.com",
    description_excerpt: "Shape the future of collaborative design tooling. Lead complex interaction paradigms, tokenized component libraries, and spatial collaboration canvases.",
    description_full: "We are seeking a Lead Product Designer to partner directly with engineering leadership in expanding Figma's design-to-code capabilities. You will conduct deep user research, produce high-fidelity prototypes, and define design specifications.",
    work_arrangement: "Remote OK",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "art-and-design",
    locations: JSON.stringify(["San Francisco, CA", "London, UK", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 165000,
    salary_max: 230000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Figma", "Design Systems", "Prototyping", "User Research", "Interaction Design", "Typography"]),
    application_url: "https://boards.greenhouse.io/figma/jobs/5910243",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 11 * 3600 * 1000)
  },
  {
    id: "ch-datadog-sre-observability",
    title: "Site Reliability Engineer (Core Observability Platform)",
    company_slug: "datadog",
    company_name: "Datadog",
    company_industry: "Cloud Monitoring & Security",
    company_logo: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80",
    company_website: "https://datadoghq.com",
    description_excerpt: "Ensure 99.999% uptime across multi-cloud clusters processing trillions of events per day. Automate incident mitigation with eBPF, Go, and Terraform.",
    description_full: "Datadog is building the monitoring and security platform for cloud applications. As an SRE on our Core Platform, you will maintain resilience at immense scale across thousands of production Kubernetes clusters.",
    work_arrangement: "Remote OK",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "engineering",
    locations: JSON.stringify(["New York, NY", "Paris, France", "Worldwide"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 145000,
    salary_max: 195000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Kubernetes", "Go", "Terraform", "Linux Internals", "eBPF", "Incident Response"]),
    application_url: "https://boards.greenhouse.io/datadog/jobs/3729101",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 14 * 3600 * 1000)
  },
  {
    id: "ch-notion-growth-marketing",
    title: "Growth Marketing Lead (Developer & Enterprise)",
    company_slug: "notion",
    company_name: "Notion",
    company_industry: "Productivity & Collaboration",
    company_logo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&auto=format&fit=crop&q=80",
    company_website: "https://notion.so",
    description_excerpt: "Drive self-serve expansion and enterprise pipeline generation through data-informed experiments, organic SEO engines, and lifecycle email automation.",
    description_full: "Notion is looking for a Growth Marketing Lead to own customer acquisition and activation funnels. You will collaborate closely with product analytics, engineering, and content teams to scale our global user base.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "marketing",
    locations: JSON.stringify(["San Francisco, CA", "New York, NY"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 150000,
    salary_max: 205000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Growth Hacking", "SEO", "Product Analytics", "A/B Testing", "Lifecycle Marketing", "SQL"]),
    application_url: "https://jobs.lever.co/notion/c91024bd",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 18 * 3600 * 1000)
  },
  {
    id: "ch-openai-research-data",
    title: "Senior Data Engineer (Pre-training Data Curation)",
    company_slug: "openai",
    company_name: "OpenAI",
    company_industry: "Artificial Intelligence & Research",
    company_logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    company_website: "https://openai.com",
    description_excerpt: "Curate and filter multi-terabyte synthetic and real-world datasets for future generations of frontier reasoning models. Ray, Spark, Python, and Azure.",
    description_full: "Join the team preparing data for training our most advanced AI models. You will design web-scale deduplication algorithms, synthetic data augmentation pipelines, and semantic quality scoring systems.",
    work_arrangement: "On-site",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "postgraduate-degree",
    taxonomy: "data-and-analytics",
    locations: JSON.stringify(["San Francisco, CA"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 245000,
    salary_max: 370000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Python", "Apache Spark", "Ray", "Data Pipelines", "NLP", "Machine Learning"]),
    application_url: "https://jobs.ashbyhq.com/openai/19820bc1",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 21 * 3600 * 1000)
  },
  {
    id: "ch-brex-enterprise-sdr",
    title: "Senior Enterprise Sales Development Representative (SDR)",
    company_slug: "brex",
    company_name: "Brex",
    company_industry: "Fintech & Corporate Cards",
    company_logo: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80",
    company_website: "https://brex.com",
    description_excerpt: "Prospect and qualify CFOs and VPs of Finance at high-growth tech unicorns. Competitive uncapped OTE, fast-track promotion to Account Executive in 12 months.",
    description_full: "As an Enterprise SDR at Brex, you will be the spearhead of our revenue engine. You will execute high-value multichannel outreach to finance leaders and book qualified meetings for our Strategic Account Executives.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "0-to-2",
    education_level: "bachelor-degree",
    taxonomy: "sales",
    locations: JSON.stringify(["Austin, TX", "Salt Lake City, UT", "Worldwide Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 65000,
    salary_max: 95000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Outbound Sales", "Salesforce", "Outreach.io", "Cold Calling", "Enterprise Prospecting", "Fintech"]),
    application_url: "https://boards.greenhouse.io/brex/jobs/4210984",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 25 * 3600 * 1000)
  },
  {
    id: "ch-vercel-frontend-astro",
    title: "Senior Frontend Engineer (Next.js & Edge Runtime)",
    company_slug: "vercel",
    company_name: "Vercel",
    company_industry: "Cloud Infrastructure & Developer Tools",
    company_logo: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=128&auto=format&fit=crop&q=80",
    company_website: "https://vercel.com",
    description_excerpt: "Build developer workflows, real-time deployment dashboards, and analytics visualizations on the edge. High-performance React, TypeScript, and Tailwind CSS.",
    description_full: "Vercel is the platform for frontend developers. We are looking for an exceptional engineer to work on our core dashboard experience, focusing on micro-interactions, accessibility, and zero-latency page transitions.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "2-to-5",
    education_level: "no-requirements",
    taxonomy: "software",
    locations: JSON.stringify(["Worldwide", "United States", "Europe"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 155000,
    salary_max: 215000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["React", "Next.js", "TypeScript", "Tailwind CSS", "Web Performance", "Edge Computing"]),
    application_url: "https://jobs.ashbyhq.com/vercel/901248ca",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 28 * 3600 * 1000)
  },
  {
    id: "ch-gitlab-devsecops",
    title: "DevSecOps & Cloud Security Architect",
    company_slug: "gitlab",
    company_name: "GitLab",
    company_industry: "DevOps & Software Delivery",
    company_logo: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80",
    company_website: "https://gitlab.com",
    description_excerpt: "Define cloud security posture, container scanning mechanisms, and automated threat mitigation pipelines for our all-remote global deployment.",
    description_full: "GitLab is an all-remote pioneer. As a DevSecOps Architect, you will establish zero-trust architectures, oversee vulnerability management programs, and collaborate with open-source contributors.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "security-and-safety",
    locations: JSON.stringify(["Worldwide", "Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 168000,
    salary_max: 228000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["DevSecOps", "Kubernetes Security", "Cloud Security", "Terraform", "CI/CD", "Compliance"]),
    application_url: "https://jobs.lever.co/gitlab/77819201",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 32 * 3600 * 1000)
  },
  {
    id: "ch-scaleai-ml-evals",
    title: "Machine Learning Evaluation Specialist",
    company_slug: "scale-ai",
    company_name: "Scale AI",
    company_industry: "Data for AI & Machine Learning",
    company_logo: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80",
    company_website: "https://scale.com",
    description_excerpt: "Evaluate frontier LLMs on coding, mathematical reasoning, and instruction following benchmarks. Write programmatic test suites and rubric guidelines.",
    description_full: "Scale AI provides the data foundation for leading AI labs. We are hiring ML Evaluation Specialists to develop benchmarks that probe edge-case reasoning, hallucination rates, and tool-use fidelity.",
    work_arrangement: "Remote OK",
    employment_types: JSON.stringify(["full-time", "contractor"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "science-and-research",
    locations: JSON.stringify(["San Francisco, CA", "Worldwide Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 135000,
    salary_max: 185000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Python", "LLM Benchmarking", "Data Analysis", "Prompt Engineering", "Evaluation Rubrics"]),
    application_url: "https://boards.greenhouse.io/scaleai/jobs/6102948",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 36 * 3600 * 1000)
  },
  {
    id: "ch-zapier-technical-support",
    title: "Tier 2 Technical Customer Support Engineer",
    company_slug: "zapier",
    company_name: "Zapier",
    company_industry: "Workflow Automation",
    company_logo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=128&auto=format&fit=crop&q=80",
    company_website: "https://zapier.com",
    description_excerpt: "Troubleshoot complex API webhooks, authentication errors, and custom code steps for developers and businesses automating workflows worldwide.",
    description_full: "Zapier is 100% remote. Our Support Engineers help customers diagnose JSON payload errors, OAuth token expirations, and custom Python/JavaScript steps in automated Zaps.",
    work_arrangement: "Remote Solely",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "0-to-2",
    education_level: "no-requirements",
    taxonomy: "customer-service-and-support",
    locations: JSON.stringify(["Worldwide Remote"]),
    is_worldwide: true,
    salary_currency: "USD",
    salary_min: 75000,
    salary_max: 105000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["REST APIs", "Webhooks", "JavaScript", "Customer Communication", "Postman", "Troubleshooting"]),
    application_url: "https://jobs.ashbyhq.com/zapier/44910283",
    direct_apply_source: "ashby",
    published_at: new Date(Date.now() - 40 * 3600 * 1000)
  },
  {
    id: "ch-retool-product-manager",
    title: "Senior Technical Product Manager (AI & Agents)",
    company_slug: "retool",
    company_name: "Retool",
    company_industry: "Internal Tools & Low-Code Platforms",
    company_logo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=128&auto=format&fit=crop&q=80",
    company_website: "https://retool.com",
    description_excerpt: "Own Retool's AI action vectors, autonomous agent builders, and enterprise vector database integrations. Work directly with Fortune 500 engineering teams.",
    description_full: "At Retool, we believe developers should build internal tools 10x faster. In this role, you will lead the roadmap for Retool AI, enabling engineers to connect enterprise data to LLM workflows seamlessly.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "5-to-10",
    education_level: "bachelor-degree",
    taxonomy: "management-and-leadership",
    locations: JSON.stringify(["San Francisco, CA", "New York, NY"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 190000,
    salary_max: 265000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Product Management", "AI Workflows", "API Design", "Developer Experience", "Roadmapping", "SQL"]),
    application_url: "https://boards.greenhouse.io/retool/jobs/5529104",
    direct_apply_source: "greenhouse",
    published_at: new Date(Date.now() - 45 * 3600 * 1000)
  },
  {
    id: "ch-ramp-financial-analyst",
    title: "Senior Financial Planning & Analysis (FP&A) Analyst",
    company_slug: "ramp",
    company_name: "Ramp",
    company_industry: "Fintech & Spend Management",
    company_logo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=128&auto=format&fit=crop&q=80",
    company_website: "https://ramp.com",
    description_excerpt: "Model revenue forecasting, unit economics, and capital efficiency across our card and billing products. Partner with executive leadership on budget strategy.",
    description_full: "Ramp is the fastest-growing financial platform in history. We are looking for an FP&A Analyst to build financial models, analyze interchange economics, and guide strategic capital allocation.",
    work_arrangement: "Hybrid",
    employment_types: JSON.stringify(["full-time"]),
    experience_level: "2-to-5",
    education_level: "bachelor-degree",
    taxonomy: "finance-and-accounting",
    locations: JSON.stringify(["New York, NY"]),
    is_worldwide: false,
    salary_currency: "USD",
    salary_min: 135000,
    salary_max: 180000,
    salary_unit: "YEAR",
    skills: JSON.stringify(["Financial Modeling", "Excel / Sheets", "SQL", "Forecasting", "SaaS Metrics", "Corporate Finance"]),
    application_url: "https://jobs.lever.co/ramp/8829104b",
    direct_apply_source: "lever",
    published_at: new Date(Date.now() - 48 * 3600 * 1000)
  }
];

async function seed() {
  const uri = 'postgresql://postgres:50h41L%40$$@localhost:5432/careerhound';
  const client = new Client({ connectionString: uri });

  try {
    await client.connect();
    console.log('Connected to PostgreSQL for seeding jobs...');

    // Clear old test rows
    await client.query('DELETE FROM jobs');

    for (const job of JOBS) {
      await client.query(`
        INSERT INTO jobs (
          id, title, company_slug, company_name, company_industry,
          company_logo, company_website, description_excerpt, description_full,
          work_arrangement, employment_types, experience_level, education_level,
          taxonomy, locations, is_worldwide, salary_currency, salary_min,
          salary_max, salary_unit, skills, application_url, direct_apply_source,
          published_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
        ) ON CONFLICT (id) DO UPDATE SET
          title = EXCLUDED.title,
          description_excerpt = EXCLUDED.description_excerpt,
          salary_min = EXCLUDED.salary_min,
          salary_max = EXCLUDED.salary_max,
          skills = EXCLUDED.skills,
          application_url = EXCLUDED.application_url;
      `, [
        job.id,
        job.title,
        job.company_slug,
        job.company_name,
        job.company_industry,
        job.company_logo,
        job.company_website,
        job.description_excerpt,
        job.description_full,
        job.work_arrangement,
        job.employment_types,
        job.experience_level,
        job.education_level,
        job.taxonomy,
        job.locations,
        job.is_worldwide,
        job.salary_currency,
        job.salary_min,
        job.salary_max,
        job.salary_unit,
        job.skills,
        job.application_url,
        job.direct_apply_source,
        job.published_at
      ]);
    }

    const countRes = await client.query('SELECT COUNT(*) FROM jobs');
    console.log(`Successfully seeded ${countRes.rows[0].count} verified direct jobs into PostgreSQL!`);
    await client.end();
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seed();
